### ISSUE TITLE
FACEBOOK_APP_ID & value of @auth

### ISSUE THREAD

**Issue by abadfish** [learn-co-curriculum/omniauth_readme#12]
I had several issues with this lesson: 
1. I believe that facebook now requires you to put ENV['FACEBOOK_APP_ID'] in the omniauth file rather than ENV['FACEBOOK_KEY']. Without it I got an error rendered by the browser that said facebook_app_id required. The readme asks us to run `export FACEBOOK_KEY=<your_key>` but I believe this should be export FACEBOOK_APP_ID=<your_key>
2. I was unable to hold my app_id or secret in memory. I'm not sure if this was me or the app but even with figaro I had to hard code them into the omniauth file to make the app function.
3. According to the lesson we are to add an #auth method to the SessionsController as follows: 

``````
def auth
    request.env['omniauth.auth']
  end ```
When you run the app in the browser and ask for a response from facebook in JSON, the '/views/sessions/create.html.erb' reads:

<pre><%= JSON.pretty_generate(@auth) %></pre>
<img src="<%= @auth[:info] && @auth[:info][:image] %>">

If you do not add **@auth** = request.env['omniauth.auth'] to the method then @auth is nil and HTTP request cannot be completed. 
``````

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by gj** [comment]
Take it w/ a grain of salt, but I had none of these problems.

**Comment by abadfish** [comment]
Thanks for sharing, Gabe.

**Comment by gj** [comment]
>Thanks for sharing, Gabe.

No problem, Kirsten!

**Comment by itzsaga** [comment]
I ran into `facebook_app_id required` as well. However, it turned out that I ran `rails s` in a different terminal than where I had run my `export`s. That could have been the problem.
