### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/omniauth_readme#18]
Facebook now requires a privacy policy in the setup for an app's to be used. They won't be able to login via the facebook login without it.

Url here for info: https://termsfeed.com/blog/privacy-policy-url-facebook-app/

**Comment by itzsaga** [comment]
I just completed without a privacy policy.

**Comment by gj** [comment]
Hey @Enoch2k2, I'm not sure this is required since we're not publishing the applications. From your link:
>This requirement is **mandatory** when you want to make your app public and have the app featured in the App Store of Facebook or whenever your app requests information from users, i.e. the **Sign-in with Facebook**.

>This means that a Privacy Policy is required for all Facebook apps – including yours – before the app is authorized to appear **live**.

Agree with @itzsaga that I'm able to complete the assignment without adding a privacy policy.
