### ISSUE TITLE
Checking the ENV variables in bash

### ISSUE THREAD

**Issue by BrunoBoehm** [learn-co-curriculum/omniauth_readme#19]
After we've done "export FACEBOOK_KEY=...", it doesn't look right to me that we can check the ENV variables by typing "Jump into the console to check that you have set the keys properly. If ENV["FACEBOOK_KEY"] and ENV["FACEBOOK_SECRET"] return your keys you're all set!"

The only way I can print those ENV variables are by doing e.g. "printenv FACEBOOK_SECRET". I think it would be good to add some more details here. Maybe it would be relavant to say that  ENV["FACEBOOK_SECRET"] can only be accessed from irb or rails c (and not just in the terminal window). 
Maybe a quick and easy way for everyone is the all-in-one commande
`export FACEBOOK_KEY=... export FACEBOOK_SECRET=... rails s`

https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps

**Comment by pianistps** [comment]
This issue is what I had trouble with. I had to ask a learn expert and he told me to run `printenv | grep FACEBOOK` . The curriculum should be more specific about showing the key and secret once set and how to do it depending on your OS.
