### ISSUE TITLE
Not registering "Pulled" on main page

### ISSUE THREAD

**Issue by bwatson78** [learn-co-curriculum/omniauth_readme#20]
![image](https://cloud.githubusercontent.com/assets/18330149/21786238/f6e5d12a-d690-11e6-9244-7e8a709db9c8.png)

**Comment by gj** [comment]
Hey @bwatson78 !

I know it's probably a bit too late for you, but, for any students who see this issue in the future, the best way to get help with lights issues is [the Ask a Question feature](help.learn.co/ask-a-question/how-to-ask-a-good-question).
