### ISSUE TITLE
The parameter app_id is required error occurred

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/omniauth_readme#26]
subject error appeared though instructions were followed

**Comment by cjbrock** [comment]
Hey @ICanDoAllThingThroughChrist! It looks like you're having an issue with executing the lab requirements, not with the curriculum itself. Head on over to Ask A Question and one of our Technical Coaches should be able to help you work out your issue.

// Corinna
