### ISSUE TITLE
Facebook automatically prepends "https" to Valid OAuth redirect URIs

### ISSUE THREAD

**Issue by kyleblee** [learn-co-curriculum/omniauth_readme#27]
In the lesson it says to add _localhost:3000/auth/facebook/callback_ to the "Valid OAuth redirect URIs" field in the Settings for your app. When this is entered, Facebook automatically prepends _https://_ onto the URL. This link (https://local:3000/auth/facebook/callback) didn't work for me, but when I finally replaced it with _http://local:3000/auth/facebook/callback_ (no s, in http), it did work. 

You might consider telling the students to add _http://local:3000/auth/facebook/callback_ to the "Valid OAuth redirect URIs" in the first place, so the prepend doesn't occur.

**Comment by lizbur10** [comment]
Prepending http:// no longer works. If you type it in and click save, you get this error: 'HTTPS is required for all Redirect URIs.'

**Comment by morgvanny** [comment]
Unfortunately for us, facebook has disabled the option that allowed you to get around this before. I believe now, you have to actually set up the local app to use HTTPS which, while not extremely hard, isn't in the scope of any of our labs

**Comment by DanielSeehausen** [comment]
resolved

Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
