### ISSUE TITLE
App Secret Location

### ISSUE THREAD

**Issue by mbalsamo2** [learn-co-curriculum/omniauth_readme#29]
The App Secret is not under Dashboard where the Readme suggests it is.
App Secret location can be found under the settings tab on the sidebar directly underneath Dashboard. Once you click on settings, you should be given a choice of Basic or Advanced. If you click on Basic you should be brought to a page that has the App Secret on it.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
