### ISSUE TITLE
Add: where to find the key and secret 

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/omniauth_readme#30]
In this section: 

Click Save Changes, and then click on Dashboard in the sidebar. Keep the page handy because we'll need those App ID and App Secret values in a minute, but first...

-- you might consider adding: 

You have to click on settings > Basic and the id and secret will be there.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
