### ISSUE TITLE
HTTPS://LOCALHOST:3000 and http parse error in terminal.

### ISSUE THREAD

**Issue by yehudamakarov** [learn-co-curriculum/omniauth_readme#31]
Running `rails s` and going to localhost in chrome, like I usually do for the labs took me to an https://localhost:3000 instead of the usual HTTP. And the HTTP request could not be parsed. (see terminal for errors.)

Then opening any other labs with `rails s` would result in similar issues, because Chrome would cache the HTTPS protocol for the localhost domain. Only clearing the cache would work 

The issue would be resolved for other labs but visiting localhost for the omniauth lab would still set the cache back to expecting an SSL certificate from anything on locahost. Even after `chrome://flags/#allow-insecure-localhost `was used. Even with safari. And I couldn't manually remove the domain security policies through chrome://net-internals/#hsts. (These are what make chrome only use HTTPS.)

This lab ships with a `config.force_ssl = true` line in the `application.rb` file, which "forces all access to the app over SSL, uses Strict-Transport-Security, and uses secure cookies."

Commenting this line of code out solves the issue. 

Apparently, so does adding the following line of code to the initializer that sets up omniauth: `OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE` - but I was not able to accomplish this. Chrome still tries to use https.

Also, see https://ieftimov.com/rails-tls-hsts-cookies

I recommend updating the lab to introduce these concepts and fixing the lab to not ship with this line of code, or supply a different workaround.

**Comment by JoeQuattrone** [comment]
This was very helpful to me as I spent nearly an hour trying to debug my  error `Invalid request: Invalid HTTP format, parsing fails.` Another thing to add is that when you comment that line out and empty your cache on chrome, make sure to type `http://localhost:3000` instead of https

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
