### ISSUE TITLE
Alternative for lesson for people without Facebook

### ISSUE THREAD

**Issue by howardemilya** [learn-co-curriculum/omniauth_readme#32]
Could someone possibly create an alternative lesson for the OmniAuth installation that doesn't require us to have a Facebook account?

I don't have an account based on principle (serious privacy concerns) and deactivated my account a long time ago. I even tried to create a new account just for this lesson with a different name and when I hit the submit button, Facebook, without my permission or even my old password, logged me into to my old personal account further confirming my lack of privacy. I seriously hate their company and would love any alternative to being logged into their system, even for just ten minutes. 

Google might have their own issues, but at least "friends" can't see how many times a day I log in or how many minutes it's been since I checked my email. So creepy with Facebook.

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
