### ISSUE TITLE
Sharing Personal Facebook Secret App Key?

### ISSUE THREAD

**Issue by SilverBright** [learn-co-curriculum/omniauth_readme#36]
I stopped coding when I was asked to cut and paste my secret Facebook App Key into the .env root file in the lab. 

In order to expose my hidden key, even to myself, I was required to enter my Facebook password.  This set off all kinds of alarm bells.

Can someone explain or confirm why this is safe to do for this lab?

Better yet, can this lab be converted to a read-me only, and disable the IDE code-along requirement completely?   

Warm Regards,
Barbara

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
