### ISSUE TITLE
Dead links?

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/omniauth_readme#4]
The link with text:
```
listen very carefully to your computer's accent when it talks to them
```
has a bad link. For some reason there is an extra '%5D'  at the end that shouldn't be there. Unfortunately I don't know how to locate the bad URL at this moment. This is the URL it currently links to: 
https://en.wikipedia.org/wiki/TCP/IP_stack_fingerprinting%5D

The link with text:
```
CAPTCHA
```
returns a 404. Url:
https://learn.co/tracks/full-stack-web-development/rails/authentication/%5Bhttps://en.wikipedia.org/wiki/CAPTCHA%5D

If I knew how to find the correct links I would have changed them myself. Sorry ^^;;

**Comment by AnnJohn** [comment]
thanks @onyoo. Will look into it.
