### ISSUE TITLE
This site can't provide a secure connection issue

### ISSUE THREAD

**Issue by Joeycho** [learn-co-curriculum/omniauth_readme#40]
Once you try to run `rails s | rails s puma | thin start - ssl`, you may got error message as the title.

This happens because of the redirection from 'http:' to 'https' automatically.

https://www.chromium.org/hsts
https://really-simple-ssl.com/knowledge-base/clear-hsts-browser/

You can check the information in the above references, and here is how I fixed my case.

1. `config.force_ssl = false` Disable all of 'config.force_ssl' from true to false. Make sure that there is no request from the server side to force to use SSL connection. (Server side)

2. I needed to delete all of cache and cookies, unfortunately. In the browser, there are some remained data for user's better experience. In this case, this prevent me request from updating. So, make sure that delete everything. In addition, `chrome://net-internals/#hsts` in this setting, make sure that query and delete all the possible combination input you may try before. I did these ones.

I run `rails s` for the server.

1. `localhost`
2. `localhost:3000`
3. `0.0.0.0`
4. `0.0.0.0:3000`
5. `178.128.14.28:38208`
6. `178.128.14.28`

Even though, I did not catch the point where it happens, but I am sure that this issue is related with the redirection from 'http://' to 'https://' by HSTS policy.

README file should be updated regarding this issue. Because it still recommend to use 'ssl' in the file. And if it is still recommended, this issue should be more discussed I think. A bit confused, but interesting issue, in terms of learning recent protocol issues! :)

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
