### ISSUE TITLE
couldn't load gems as is 

### ISSUE THREAD

**Issue by mackenzie-km** [learn-co-curriculum/omniauth_readme#41]
error:
Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
(even though sqlite3 was in the gemfile & was showing as a gem that bundler used)

solution:
change it to gem "sqlite3", "~> 1.3.6" in gemfile.
delete gem lockfile. 
run bundle install.

error:
Array values in the parameter to `Gem.paths=` are deprecated.
Please use a String or nil.

solution (in terminal):
bundle update spring
bundle exec spring binstub --remove --all
bundle exec spring binstub --all

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
