### ISSUE TITLE
Bundler incompatible with omniauth

### ISSUE THREAD

**Issue by Madeline-Stark** [learn-co-curriculum/omniauth_readme#42]
Some students have been experiencing this error:

Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    rails (~> 4.2) was resolved to 4.2.11.1, which depends on
      bundler (>= 1.3.0, < 2.0)

  Current Bundler version:
    bundler (2.0.2)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running &#96;gem install
bundler&#96;?

Could not find gem 'bundler (>= 1.3.0, < 2.0)', which is
required by gem 'rails (~> 4.2)', in any of the sources.

We fixed the error by downgrading bundler:
gem uninstall bundler
gem install bundler --version '1.0.0'

https://stackoverflow.com/questions/9725811/how-to-downgrade-bundler-or-upgrade-rails

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
