### ISSUE TITLE
Issue of incompatibility with latest sqlite3 version

### ISSUE THREAD

**Issue by Terry-Thompson** [learn-co-curriculum/omniauth_readme#48]
Received the following error:
`// ♥ rails g resource users name:string email:string image:string uid:string
/Users/terrythompson/.rvm/gems/ruby-2.6.1/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
/Users/terrythompson/.rvm/gems/ruby-2.6.1/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/connection_specification.rb:177:in 'rescue in spec': Specified 'sqlite3' for database adapter, but the gem is not loaded. Add gem 'sqlite3' to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
`

Error was corrected by changing sqlite version in the Gemfile:
`gem 'sqlite3', '~>1.3.6'`
and deleting the Gemfile.lock file.  

Thank you

**Comment by drakeltheryuujin** [comment]
Thanks for the feedback @Terry-Thompson,

I was actually just updating the Gemfile now and you beat me to it. This will be remedied shortly.

Thanks for your contribution!
