### ISSUE TITLE
FB uid's coming back as too big for active record "out of range for integer limit 4"

### ISSUE THREAD

**Issue by jd2rogers2** [learn-co-curriculum/omniauth_readme#49]
```
ActiveModel::RangeError in SessionsController#create 10156169878546619 is out of range for ActiveModel::Type::Integer with limit 4
```

when fb passes back the data from oauth we get an id with 16 characters, this is too big for activeRecord to handle in an integer column

use column type bigint or use limit -> `t.integer "uid", limit: 16`

**Comment by drakeltheryuujin** [comment]
Thank you for providing feedback!
The instructions suggest to use type `String` for each, attribute, including `uid`:
```
The User model should have four attributes, all strings: name, email, image, and uid (the user's ID on Facebook)
```
This should resolve any issues with it being considered "out of range".
If you do not believe that this issue has been addressed, please re-open this issue. 💙
