### ISSUE TITLE
Resources Link Does Not Link to Appropriate Resource

### ISSUE THREAD

**Issue by damianmalysza** [learn-co-curriculum/omniauth_readme#61]
The 'Managing Environment Variables' link under 'Resources' does not take you to an article. The https://launchschool.com/blog/managing-environment-configuration-variables-in-rails link just redirects to the launchschool.com home page.

**Comment by graciemcguire** [comment]
Hi @damianmalysza thanks for flagging this. We have removed the broken link. 
Thanks!
