### ISSUE TITLE
Privacy Error block.

### ISSUE THREAD

**Issue by LGmedia954** [learn-co-curriculum/omniauth_readme#63]
Description of Issue:

1.  thin start --ssl with https:// (secure) does not escape the Privacy Error block.

2.  Only rails s and http:// (nonsecure) is proceeding to Facebook log in page with the message: "Insecure Login Blocked.  You can't get an access token or log in to this app from an insecure page. Try re-loading the page as https://"

**Comment by lizbur10** [comment]
Hello! Thanks for posting this issue and providing feedback.

I have worked through the lab and I was not able to recreate the issue so I am going to close it. If you can provide any additional details - the steps you followed that resulted in the error, which OS you're using, the steps you tried to resolve the issue, etc. - please reopen this issue.

Thank you for contributing to the Flatiron School curriculum! 💙
