### ISSUE TITLE
Updated Facebook Login API

### ISSUE THREAD

**Issue by karsonkalt** [learn-co-curriculum/omniauth_readme#65]
### Canvas Link

https://learning.flatironschool.com/courses/1881/assignments/125547?module_item_id=259464

### Concern

The Facebook login API requires "Advanced Access" to be enabled on the app for Omniauth. I believe this has changed slightly since the lab was created. The screenshot below is what a student and I had to enable today to get the app running.

![cpladW5F6mawIBqZ9vCpmf5puPG-ZqM71w](https://user-images.githubusercontent.com/15637664/146258571-3a8f800b-9490-438a-9872-fa612a4daf47.png)

https://developers.facebook.com/docs/graph-api/overview/access-levels/

**Comment by lizbur10** [comment]
Thanks @karsonkalt ! This update has been made 💙
