### ISSUE TITLE
Issue running `thin start -ssl` on Windows

### ISSUE THREAD

**Issue by karsonkalt** [learn-co-curriculum/omniauth_readme#66]
### Canvas Link

https://learning.flatironschool.com/courses/1881/assignments/125547?module_item_id=259464

### Concern

Running `thin start --ssl` on a windows machine creates the following Assertion Error.
<img width="372" alt="Screen Shot 2021-12-16 at 3 34 33 PM" src="https://user-images.githubusercontent.com/15637664/146445414-206dcb71-baec-4638-9bc9-26457737b2be.png">

I have asked students to run `rails start` instead and we do not see the assertion error and are able to follow through the Omniauth link.

**Comment by ihollander** [comment]
@karsonkalt this one looks a bit tricky! From what I can tell, Facebook requires a SSL url for OAuth, so using SSL is required. I'll see if there are other OAuth providers that don't have this requirement, since setting up SSL is another layer of complexity on an already tricky lab.
